import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "../lib/utils"
import {Header}  from "../components/header";
import {Footer}  from "../components/footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export const metadata: Metadata = {
  title: "CranioCom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className={cn(
            "min-h-screen bg-black font-sans antialiased text-text-primary",
            fontSans.variable
          )}
        >
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
